name: dropdown_widgets
description: A widget for selecting multiple options from a dropdown list.
version: 0.0.2
homepage: https://github.com/archie934/multi_select_dropdown

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

